[project]
name = "module1"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/fanjum/Documents/web3/stacks_sc/projects/my_projs/multisafe-stages/module1/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.multisafe]
path = "contracts/multisafe.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
